function val=importATMdata(fileToRead1)
    %IMPORTFILE(FILETOREAD1)
    %  Imports data from the specified file
    %  FILETOREAD1:  file to read

    %  Auto-generated by MATLAB on 05-Nov-2010 16:59:06

    DELIMITER = ' ';
    HEADERLINES = 11;

    % Import the file
    val = importdata(fileToRead1, DELIMITER, HEADERLINES);
    val=val.data;
    
    % Donnees
    % Altitude géodésique
    % Rho
    % Vson
end
